---
version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.8.0'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  broker:
    image: 'bitnami/kafka:3.1.1'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8082:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - broker

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  auth:
    build: auth
    env_file: ./auth/.env
    command: ['rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    volumes:
      - ./auth:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - broker

  tasks:
    build: tasks
    env_file: ./tasks/.env
    volumes:
      - ./tasks:/app
    ports:
      - "3010:3000"
    environment:
      TEST_BROWSER: chrome
      TEST_BROWSER_URL: http://chrome-server:4444
    depends_on:
      - db
      - broker
      - chrome-server

  accounting:
    build: accounting
    env_file: ./accounting/.env
    volumes:
      - ./accounting:/app
    ports:
      - "3020:3000"
    environment:
      TEST_BROWSER: chrome
      TEST_BROWSER_URL: http://chrome-server:4444
    depends_on:
      - db
      - broker
      - chrome-server

  analytics:
    build: analytics
    env_file: ./analytics/.env
    volumes:
      - ./analytics:/app
    ports:
      - "3030:3000"
    environment:
      TEST_BROWSER: chrome
      TEST_BROWSER_URL: http://chrome-server:4444
    depends_on:
      - db
      - broker
      - chrome-server

  chrome-server:
    image: selenium/standalone-chrome:106.0
    ports:
      - "7900:7900" # пароль для подключения secret

  firefox-server:
    image: selenium/standalone-firefox:97.0
    ports:
      - "7901:7900" # пароль для подключения secret

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT:-8080}:8080

volumes:
  postgres_data:
