inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Rails/I18nLocaleTexts:
  Enabled: false
Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/**/*'

RSpec/ContextWording:
  Exclude:
    - 'spec/system/**/*'
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/system/**/*'
