require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

inherit_from:
  - https://gist.githubusercontent.com/beglov/9da03971bae1ac549e2c570d052451f2/raw/7005950f3974dc69f0ca09f4f257b894e4dc4b35/rubocop.yml
  - .rubocop_todo.yml
