development:
  client_id: "accounting_service"
  group_id_prefix: "accounting_service."
  brokers:
    - <%= ENV['KAFKA_BROKER'] %>

test:
  client_id: "accounting_service"
  group_id_prefix: "accounting_service."
  brokers:
    - <%= ENV['KAFKA_BROKER'] %>

production:
  client_id: "accounting_service"
  group_id_prefix: "accounting_service."
  brokers:
    - <%= ENV['KAFKA_BROKER'] %>
