development:
  client_id: "analytics_service"
  group_id_prefix: "analytics_service."
  brokers:
    - <%= ENV['KAFKA_BROKER'] %>

test:
  client_id: "analytics_service"
  group_id_prefix: "analytics_service."
  brokers:
    - <%= ENV['KAFKA_BROKER'] %>

production:
  client_id: "analytics_service"
  group_id_prefix: "analytics_service."
  brokers:
    - <%= ENV['KAFKA_BROKER'] %>
